version: "3.7"

services:
  app:
    build: "./dist/docker/app"
    volumes:
      - ".:/app"
    links:
      - "database"
      - "event-bus"
    ports:
    - "1337:1337"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api_photos.rule=Host(`ms.storage.keepsake.traefik.me`)"
      - "traefik.http.services.api_photos.loadbalancer.server.port=1337"

  database:
    image: "postgres:alpine"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - "./var/data/postgresql:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  event-bus:
    hostname: "rabbitmq"
    image: "rabbitmq:management"
    volumes:
      - "./var/data/rabbitmq:/var/lib/rabbitmq"
    ports:
    - "15672:15672"

  storage:
    image: minio/minio
    volumes:
      - ./var/data/minio:/data
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    env_file:
      - .env
    ports:
    - "9000:9000"
