services:
    _defaults:
        autowire: true
        autoconfigure: true

    Storage\:
        resource: '../src'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    Storage\Action\:
        resource: '../src/Action/'
        tags: ['controller.service_arguments']

    Jmoati\ExifTool\ExifTool: ~
